### PR TITLE
update to use gulp-clean-css instead of deprecated gulp-minify-css

### PR DESCRIPTION
**Pull request by chmontgomery**

### CODE REVIEW

**Comment by chmontgomery** [comment]
@hazmeister @clocked0ne update to use `gulp-clean-css` now in `v2.25.0`. If you have time, please test and let me know how it works. Thanks!

**Comment by clocked0ne** [comment]
Excellent, I had just had a trial of the updates on my machine and kept having issues with the integration tests failing, so thank you! We are testing it right now :)

**Comment by clocked0ne** [comment]
@chmontgomery It works fine, we have tested with node v6.x.0 too which is where our errors were manifesting themselves

**Comment by hazmeister** [comment]
Cheers @chmontgomery! We're now using node 6.1.0!

**Pull request merged**
