### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by okvic77**
Still missing test, I don't really know if it works.

I try to test this but many dev dependencies throw errors. I don't know whats going on with them.

### CODE REVIEW

**Comment by okvic77** [comment]
some test are broken for a \n string. Less compilation with \n and the end.

**Comment by chmontgomery** [comment]
thanks for the PR! I'll take a look soon and get back to you.

**Comment by chmontgomery** [comment]
I was just looking at this again today. Looks like there is now another package in existence for doing css compression: [`gulp-clean-css`](https://github.com/scniro/gulp-clean-css). Anyone know the difference between that and [`gulp-cssnano`](https://github.com/ben-eb/gulp-cssnano)? Is one better over the other?

**Comment by clocked0ne** [comment]
```gulp-clean-css``` appears to be the more direct replacement for ```gulp-minify-css``` but both support sourcemaps, etc so I don't think there is a great deal of difference. ```gulp-clean-css``` is supposedly one of the best performing in benchmarks - I'd go with that

**Comment by chmontgomery** [comment]
@clocked0ne cool thanks for the info. I'll likely go that route.

**Comment by hazmeister** [comment]
Hi,

Any update on this?  We're unable to move to Node 6.0.0 due to a problem that has been fixed in the latest version of gulp-clean-css:
https://github.com/scniro/gulp-clean-css/issues/4

Any chance this PR will get nudged along?

**Comment by chmontgomery** [comment]
@hazmeister I can look at this again today

**Comment by chmontgomery** [comment]
created new PR using `gulp-clean-css` here https://github.com/dowjones/gulp-bundle-assets/pull/83

**Comment by chmontgomery** [comment]
thanks for the participation everyone. You can follow progress on the new PR thread: https://github.com/dowjones/gulp-bundle-assets/pull/83

**Pull request closed without merging**
